---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: script-develop-stage-local-com
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      branch: develop
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontend
        branch: develop
    spec:
      containers:
      - image: registry.gimaym.com/frontend:develop
        name: frontend
        restartPolicy: 
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "0.100"
            memory: "400Mi"
          requests:
            cpu: "0.010"
            memory: "200Mi"
        env:
         - name: VUE_APP_API_URI
           valueFrom:
             configMapKeyRef:
               name: frontend-configmap
               key: VUE_APP_API_URI
         - name: VUE_APP_SOCKET_URI
           valueFrom:
             configMapKeyRef:
               name: frontend-configmap
               key: VUE_APP_SOCKET_URI
         - name: VUE_APP_PRODUCTION_MODE
           valueFrom:
             configMapKeyRef:
               name: frontend-configmap
               key: VUE_APP_PRODUCTION_MODE
        ports:
        - containerPort: 80
          name: frontend
        readinessProbe:
          httpGet:
            path: /
            port: frontend
          initialDelaySeconds: 160
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /
            port: frontend
          initialDelaySeconds: 160
          periodSeconds: 60
        volumeMounts:
          - name: etcdcerts-configmap
            mountPath: /certs
          - name: frontend-configmap
            mountPath: /etc/nginx/conf.d/default.conf
            readOnly: true
            subPath: default.conf
      volumes:
      - name: etcdcerts-configmap
        configMap:
          name: etcdcerts-config
      - name: frontend-configmap
        configMap:
          name: frontend-configmap
          items:
          - key: default.conf
            path: default.conf
      imagePullSecrets:
      - name: registrygimaymcom

