---
apiVersion: v1
kind: Service
metadata:
  namespace: script-develop-stage-local-com
  name: frontend-svc
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
  - name: frontend
    protocol: TCP
    port: 4000
    targetPort: 80
  selector:
    app: frontend
    branch: develop