export const SET_DRAWER = 'SET_DRAWER';
export const SET_CURRENT_VIEW = 'SET_CURRENT_VIEW';
export const SET_ACCOUNTS = 'SET_ACCOUNTS';
export const SET_APP_READY = 'SET_APP_READY';
export const SET_CENTRIFUGE_CONNECTED_FLAG = 'SET_CENTRIFUGE_CONNECTED_FLAG';
